matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - lib32stdc++6 # https://github.com/flutter/flutter/issues/6207
            - libstdc++6
            - fonts-droid
      before_script:
        - wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
        - mkdir android-sdk
        - unzip -qq sdk-tools-linux-3859397.zip -d android-sdk
        - export ANDROID_HOME=`pwd`/android-sdk
        - export PATH=`pwd`/android-sdk/tools/bin:$PATH
        - mkdir -p /home/travis/.android # silence sdkmanager warning
        - echo 'count=0' > /home/travis/.android/repositories.cfg # silence sdkmanager warning
        - echo y | sdkmanager "tools"
        - echo y | sdkmanager "platform-tools"
        - echo y | sdkmanager "build-tools;25.0.3"
        - echo y | sdkmanager "platforms;android-25"
        - echo y | sdkmanager "extras;android;m2repository"
        - echo y | sdkmanager "extras;google;m2repository"
        - echo y | sdkmanager "patcher;v4"
        - sdkmanager --list
        - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
        - unzip -qq gradle-3.5-bin.zip
        - export GRADLE_HOME=$PWD/gradle-3.5
        - export PATH=$GRADLE_HOME/bin:$PATH
        - gradle -v
        - ./travis_setup.sh
        - ./flutter/bin/flutter doctor
      script:
      #  - ./flutter/bin/flutter test
      #  - ./flutter/bin/flutter -v run --trace-startup --no-hot
        - ./flutter/bin/flutter -v build apk


      after_success:
        - sh set_tags.sh

      notifications:
        email: true

      deploy:
        provider: releases
        api_key:
          secure: wy43X9WESaODgKXr/ccu8OneJQzqrzy84XZcZ1KA74HN2oZzm+NAZbm1FcrzUBbyvtDWMtV8TDArsYSs4SpMMpeSdJbTkK/IMhhFZxvyQ4XBM6YEdkCKnIuLFuFTgIicHlvtbujClOLX0n+dyAKhFyXBH2N53QurmeqlLaYcMXJCdhtnNw7H+8jB/BOvhlR1j5OpG4gQQjio+1YTNGvKu6b0l8yYcLR3i0+YLVhIozwbet12GXrY/nvJAd5fwKe5hqHpGqMIVEqtSBIA+nfijPOYclHal7D3BfRP77jO/dklkAOygLxEzZQiVkfTIWREBbOsllj5bivCbZUmKhQc1lo/Wp+XPC+AO8mnBVOfYHW9l62e+pVieGDdbAdKw7vPIXBHmw2QTSbboRnQMHqU+tNXb2BmZkJGtZaHDwoPZ6xjsbxctSCpm8mn+VV1uOSBp7mHx4iXXqW+Q5YiQ2d5I3fdiAko54g4hT40KIYfSpE4022kzF42BU3apzCnpRhQnAvJid3KEdUAXANXkSxo00WC0lEx2LzxDKzNrheEmPb/uXAQa3OwpKgMP/yI1mrZ0IvAAc9q6NNxHJPeKil6yVQRLexGs3QqjAEwbN4pw1mq1V4zzoBi3Vxb9czKl6iAmVYvF1OY+ZqBHJTBdCHiTiOEbDZVG5yr7j+8VGL/lJw=
        file: BS/build/outputs/apk/BS*release*.apk
        file_glob: "true"
        skip_cleanup: true
        on:
          branch: master
          repo: chammub/BS

cache:
  directories:
    - $HOME/.pub-cache