name: bhavani_shoppe
description: Bhavani Shoppee Mobile Application

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  # color package
  color: any
  # store values locally
  shared_preferences: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: res/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: res/fonts/Poppins-Regular.ttf
          weight: 400

  assets:
    # images
    - res/images/ic_logo.png
    - res/images/ic_logo_text.png
    - res/images/ic_bg_home.png

    # menu buttons
    - res/images/ic_about.png
    - res/images/ic_food.png
    - res/images/ic_mattress.png
    - res/images/ic_textile.png

    # food app
    - res/images/ic_pizza.png
    - res/images/ic_pizza_full.png

    - res/images/ic_food_menu_italian.png
    - res/images/ic_food_menu_mexican.png
    - res/images/ic_food_menu_burger.png
    - res/images/ic_food_menu_pizza.png

    - res/images/ic_veg_icon.png
    - res/images/ic_non_veg_icon.png
    - res/images/ic_food_duration.png
    - res/images/ic_banner_bhavani_exclusive.png
    - res/images/ic_banner_must_try.png
    - res/images/ic_banner_new.png
