name: bhavani_shoppe
description: Bhavani Shoppee Mobile Application

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

  # color package
  color: any

  # store values locally
  shared_preferences: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: res/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: res/fonts/Poppins-Regular.ttf
          weight: 400

  assets:
    # images
    - res/images/ic_logo.png
    - res/images/ic_logo_text.png
    - res/images/ic_bg_home.png

    # menu buttons
    - res/images/ic_about.png
    - res/images/ic_food.png
    - res/images/ic_mattress.png
    - res/images/ic_textile.png

    # food app
    - res/images/ic_pizza.png
    - res/images/ic_pizza_full.png

    - res/images/ic_food_menu_italian.png
    - res/images/ic_food_menu_mexican.png
    - res/images/ic_food_menu_burger.png
    - res/images/ic_food_menu_pizza.png

    - res/images/ic_veg_icon.png
    - res/images/ic_non_veg_icon.png
    - res/images/ic_food_duration.png
    - res/images/ic_banner_bhavani_exclusive.png
    - res/images/ic_banner_must_try.png
    - res/images/ic_banner_new.png

    # mock data
    - lib/mockData/food_home_screen_data.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
